name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build app Staging
        if: github.ref == 'refs/heads/develop'
        env:
          APP_URL: https://staging.taylors-version.com
          CLIENT_ID: 8c8f303eba3b4e1bab345f245d4b1036
        run: npm run build
      - name: Build app Prod
        if: github.ref == 'refs/heads/master'
        env:
          APP_URL: https://taylors-version.com
          CLIENT_ID: 1b5718d03b174bfb8988f14bfac422a6
        run: npm run build
      - name: Push build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Install and build CDK
        working-directory: cdk
        run: |
          npm ci
          npm run build
      - name: Add CDK to PATH
        working-directory: cdk
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH
      - name: Deploy stack Staging
        if: github.ref == 'refs/heads/develop'
        working-directory: cdk
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEPLOY_REGION: eu-west-1
          PROD: false
        run: |
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/eu-west-1 -c domain=taylors-version.com -c subdomain=staging
          cdk deploy TaylorsVersionStaging -c domain=taylors-version.com -c subdomain=staging --require-approval never
      - name: Deploy stack Prod
        if: github.ref == 'refs/heads/master'
        working-directory: cdk
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEPLOY_REGION: eu-west-1
          PROD: true
        run: |
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/eu-west-1 -c domain=taylors-version.com
          cdk deploy TaylorsVersionProd -c domain=taylors-version.com --require-approval never