name: Deploy Staging
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build app
        env:
          APP_URL: https://staging.${{ secrets.APP_DOMAIN }}
        run: npm run build
      - name: Push build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Install and build CDK
        run: |
          cd ./cdk
          npm install -g aws-cdk
          npm install
          npm run build
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: deploy
          cdk_args: --require-approval never -c domain=staging.${{ secrets.APP_DOMAIN }}
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1